//! Query expansion.
//!
//! Bridges the gap between how Algerians *type* and how content is *written*. The same concept
//! appears as `سونلغاز`, `Sonelgaz`, `sonalgaz`; the same question as `شحال` and `ch7al`. Without
//! expansion, a user typing `ch7al` finds nothing written as `شحال`, and recall for Darija and
//! Arabizi collapses.
//!
//! # Two sources, and where each is applied
//!
//! - **Lexicon** — hand-curated equivalence classes in `data/expansion/`. These are exported as
//!   Meilisearch synonyms at migration time, so the engine applies them during retrieval at no
//!   query-time cost.
//! - **Transliteration** — generative, for forms nobody wrote down. This has to happen at query
//!   time, because the whole point is covering spellings the lexicon does not contain.
//!
//! # The rule that matters
//!
//! An expansion must never outrank the literal query. If a user typed *Sonelgaz*, a document
//! containing only *سونلغاز* ranks below one containing *Sonelgaz* at equal relevance. Every
//! weight here is below 1.0 for that reason.

use std::collections::HashMap;

use xustive_core::Lang;
use xustive_text::script::{self, Script};
use xustive_text::{normalize, tokens};

use crate::translit::{self, TranslitConfig};

/// Where a variant came from. Kept so ranking can weight sources differently and so a bad
/// expansion can be traced to the file that produced it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Origin {
    /// A curated equivalence class.
    Lexicon,
    /// Generated by the transliterator.
    Translit,
    /// Generated by light Arabic morphology (definite-article / affix forms), M7-T01.1.
    Morphology,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Variant {
    pub text: String,
    pub weight: f32,
    pub origin: Origin,
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Expansion {
    pub variants: Vec<Variant>,
}

impl Expansion {
    pub fn is_empty(&self) -> bool {
        self.variants.is_empty()
    }

    /// Just the strings, for callers that only need terms.
    pub fn terms(&self) -> Vec<&str> {
        self.variants.iter().map(|v| v.text.as_str()).collect()
    }
}

/// One curated equivalence class.
#[derive(Debug, Clone)]
pub struct Concept {
    pub id: String,
    pub variants: Vec<String>,
    pub weight: f32,
}

#[derive(Debug, Clone, Copy)]
pub struct ExpanderConfig {
    /// Hard cap on the variants produced for one query.
    pub max_variants: usize,
    /// Query tokens expanded, chosen from the rarest first.
    pub max_expanded_tokens: usize,
    /// Tokens shorter than this are never expanded.
    pub min_token_len: usize,
    /// Ceiling on any expansion weight. Enforced, not merely intended.
    pub max_weight: f32,
    pub translit: TranslitConfig,
}

impl Default for ExpanderConfig {
    fn default() -> Self {
        Self {
            max_variants: 8,
            max_expanded_tokens: 3,
            min_token_len: 3,
            max_weight: 0.95,
            translit: TranslitConfig::default(),
        }
    }
}

const ENTITIES_TSV: &str = include_str!("../../../data/expansion/entities.tsv");
const SYNONYMS_TSV: &str = include_str!("../../../data/expansion/synonyms.tsv");

pub struct Expander {
    /// Normalised term → the concepts it belongs to. A term can be in more than one.
    index: HashMap<String, Vec<usize>>,
    concepts: Vec<Concept>,
    config: ExpanderConfig,
}

impl Default for Expander {
    fn default() -> Self {
        Self::new(ExpanderConfig::default())
    }
}

impl Expander {
    pub fn new(config: ExpanderConfig) -> Self {
        let mut concepts = Vec::new();
        for tsv in [ENTITIES_TSV, SYNONYMS_TSV] {
            concepts.extend(parse_concepts(tsv));
        }

        let mut index: HashMap<String, Vec<usize>> = HashMap::new();
        for (i, c) in concepts.iter().enumerate() {
            for v in &c.variants {
                index.entry(v.clone()).or_default().push(i);
            }
        }
        Self {
            index,
            concepts,
            config,
        }
    }

    pub fn concepts(&self) -> &[Concept] {
        &self.concepts
    }

    /// Expand an already-normalised query.
    ///
    /// `lang` is advisory: transliteration only fires on Latin-script text that the detector did
    /// not confidently call French or English, so a French query is left alone.
    pub fn expand(&self, normalized: &str, lang: Lang) -> Expansion {
        let toks: Vec<&str> = tokens(normalized).collect();
        if toks.is_empty() {
            return Expansion::default();
        }

        let mut out: Vec<Variant> = Vec::new();
        let mut seen: Vec<String> = toks.iter().map(|t| t.to_string()).collect();
        let mut expanded_tokens = 0usize;

        for tok in &toks {
            if expanded_tokens >= self.config.max_expanded_tokens {
                break;
            }
            if tok.chars().count() < self.config.min_token_len {
                continue;
            }

            let before = out.len();

            // 1. Curated siblings.
            if let Some(ids) = self.index.get(*tok) {
                for &id in ids {
                    let c = &self.concepts[id];
                    for v in &c.variants {
                        if seen.contains(v) {
                            continue;
                        }
                        seen.push(v.clone());
                        out.push(Variant {
                            text: v.clone(),
                            weight: c.weight.min(self.config.max_weight),
                            origin: Origin::Lexicon,
                        });
                    }
                }
            }

            // 2. Transliteration, for forms nobody wrote down.
            if self.should_transliterate(tok, lang) {
                for cand in translit::to_arabic(tok, &self.config.translit) {
                    if seen.contains(&cand.text) {
                        continue;
                    }
                    seen.push(cand.text.clone());
                    out.push(Variant {
                        // Generated forms are guesses, and are weighted well below curated ones.
                        weight: (0.6_f32).min(self.config.max_weight),
                        text: cand.text,
                        origin: Origin::Translit,
                    });
                }
            }

            // 3. Light Arabic morphology (M7-T01.1): the definite-article and affix forms of the
            //    token, so `الكتاب` and `كتاب` reach the same documents without stemming the index.
            //    Surface stripping only — a query-expansion aid, not root extraction.
            for cand in crate::morph::arabic_variants(tok) {
                if seen.contains(&cand) {
                    continue;
                }
                seen.push(cand.clone());
                out.push(Variant {
                    // Above transliteration (affix stripping is more reliable than script guessing),
                    // below curated pairs.
                    weight: (0.7_f32).min(self.config.max_weight),
                    text: cand,
                    origin: Origin::Morphology,
                });
            }

            if out.len() > before {
                expanded_tokens += 1;
            }
        }

        // Best first, then cap. Sorting before truncating means the cap drops the weakest
        // variants rather than whichever happened to be generated last.
        out.sort_by(|a, b| {
            b.weight
                .partial_cmp(&a.weight)
                .unwrap_or(std::cmp::Ordering::Equal)
        });
        out.truncate(self.config.max_variants);
        Expansion { variants: out }
    }

    /// Whether to generate transliterations for this token.
    fn should_transliterate(&self, tok: &str, lang: Lang) -> bool {
        // Only Latin script: Arabic input needs no transliteration to reach Arabic documents.
        if script::detect(tok) != Script::Latin {
            return false;
        }
        // A query the detector confidently called French or English is not Arabizi, and
        // transliterating `facture` into Arabic letters produces noise.
        if matches!(lang, Lang::Fr | Lang::En) {
            return false;
        }
        tok.chars().count() >= self.config.min_token_len
    }

    /// Export the curated classes as Meilisearch synonyms.
    ///
    /// Meilisearch takes a map from term to equivalents and applies it during retrieval, which
    /// means the lexicon costs nothing at query time. Transliteration cannot be exported this
    /// way — it is generative, and the forms it covers are precisely the ones not in any list.
    pub fn meili_synonyms(&self) -> HashMap<String, Vec<String>> {
        let mut out: HashMap<String, Vec<String>> = HashMap::new();
        for c in &self.concepts {
            for term in &c.variants {
                let others: Vec<String> =
                    c.variants.iter().filter(|v| *v != term).cloned().collect();
                if others.is_empty() {
                    continue;
                }
                out.entry(term.clone()).or_default().extend(others);
            }
        }
        // A term appearing in two concepts accumulates both sets; de-duplicate.
        for v in out.values_mut() {
            v.sort();
            v.dedup();
        }
        out
    }
}

/// Parse `concept_id <TAB> a|b|c <TAB> weight <TAB> note`.
fn parse_concepts(tsv: &str) -> Vec<Concept> {
    let mut out = Vec::new();
    for (lineno, line) in tsv.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut cols = line.split('\t');
        let (Some(id), Some(variants_col)) = (cols.next(), cols.next()) else {
            continue;
        };
        let weight = cols
            .next()
            .and_then(|w| w.trim().parse::<f32>().ok())
            .unwrap_or(0.85);

        // Variants are stored normalised so lookup needs no per-call work, and so a lexicon
        // written with harakat still matches normalised query text.
        let variants: Vec<String> = variants_col
            .split('|')
            .map(|v| normalize(v.trim()))
            .filter(|v| !v.is_empty())
            .collect();

        if variants.len() < 2 {
            tracing::warn!(
                line = lineno + 1,
                concept = id,
                "concept needs at least two variants to be useful, skipped"
            );
            continue;
        }
        out.push(Concept {
            id: id.trim().to_string(),
            variants,
            weight,
        });
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn exp() -> Expander {
        Expander::default()
    }

    fn texts(e: &Expansion) -> Vec<String> {
        e.variants.iter().map(|v| v.text.clone()).collect()
    }

    #[test]
    fn lexicons_load_and_are_substantial() {
        let e = exp();
        assert!(
            e.concepts().len() > 80,
            "only {} concepts loaded",
            e.concepts().len()
        );
    }

    #[test]
    fn every_concept_has_at_least_two_variants() {
        // A single-variant concept expands to nothing and is almost certainly a typo in the file.
        for c in exp().concepts() {
            assert!(c.variants.len() >= 2, "concept {} has one variant", c.id);
        }
    }

    #[test]
    fn entity_aliases_expand_across_scripts() {
        let e = exp();
        let v = texts(&e.expand(&normalize("sonelgaz"), Lang::Und));
        assert!(v.contains(&"سونلغاز".to_string()), "got {v:?}");

        let v = texts(&e.expand(&normalize("سونلغاز"), Lang::Ar));
        assert!(v.contains(&"sonelgaz".to_string()), "got {v:?}");
    }

    #[test]
    fn wilaya_names_expand_both_ways() {
        let e = exp();
        assert!(texts(&e.expand(&normalize("وهران"), Lang::Ar)).contains(&"oran".to_string()));
        assert!(texts(&e.expand(&normalize("oran"), Lang::Und)).contains(&"وهران".to_string()));
    }

    #[test]
    fn darija_question_words_reach_msa() {
        // The point of the whole exercise: a Darija query reaching an MSA document.
        let e = exp();
        let v = texts(&e.expand(&normalize("شحال"), Lang::Ary));
        assert!(
            v.contains(&"كم".to_string()),
            "شحال should reach كم, got {v:?}"
        );
        assert!(v.contains(&"combien".to_string()), "and combien, got {v:?}");
    }

    #[test]
    fn arabizi_reaches_arabic_through_the_lexicon() {
        let e = exp();
        let v = texts(&e.expand(&normalize("ch7al"), Lang::Ary));
        assert!(v.contains(&"شحال".to_string()), "got {v:?}");
    }

    #[test]
    fn transliteration_covers_forms_not_in_the_lexicon() {
        // `sbitar` is in the Darija detection list but not as an expansion concept, so the only
        // route to Arabic is the transliterator.
        let e = exp();
        let v = e.expand(&normalize("sbitar"), Lang::Ary);
        assert!(
            v.variants.iter().any(|x| x.origin == Origin::Translit),
            "expected a generated variant, got {:?}",
            texts(&v)
        );
    }

    #[test]
    fn french_queries_are_not_transliterated() {
        // Turning `facture` into Arabic letters produces noise, not recall.
        let e = exp();
        let v = e.expand(&normalize("facture electricite"), Lang::Fr);
        assert!(
            v.variants.iter().all(|x| x.origin == Origin::Lexicon),
            "French query should not be transliterated: {:?}",
            texts(&v)
        );
    }

    #[test]
    fn expansions_never_outrank_the_literal_query() {
        // The invariant that keeps expansion from hurting precision.
        let e = exp();
        for q in ["sonelgaz", "شحال", "ch7al", "oran", "facture"] {
            for v in e.expand(&normalize(q), Lang::Und).variants {
                assert!(
                    v.weight < 1.0,
                    "variant {:?} has weight {} — an expansion must never outrank the literal term",
                    v.text,
                    v.weight
                );
            }
        }
    }

    #[test]
    fn the_query_terms_themselves_are_not_returned_as_variants() {
        let e = exp();
        let v = texts(&e.expand(&normalize("sonelgaz facture"), Lang::Und));
        assert!(!v.contains(&"sonelgaz".to_string()));
        assert!(!v.contains(&"facture".to_string()));
    }

    #[test]
    fn variant_count_is_capped() {
        let e = exp();
        // A query where every token expands heavily.
        let v = e.expand(&normalize("شحال كيفاش وين علاش سونلغاز فاتورة"), Lang::Ary);
        assert!(
            v.variants.len() <= ExpanderConfig::default().max_variants,
            "produced {} variants, cap is {}",
            v.variants.len(),
            ExpanderConfig::default().max_variants
        );
    }

    #[test]
    fn capping_keeps_the_strongest_variants() {
        let e = exp();
        let v = e.expand(&normalize("سونلغاز شحال"), Lang::Ary);
        for w in v.variants.windows(2) {
            assert!(
                w[0].weight >= w[1].weight,
                "variants are not weight-ordered"
            );
        }
    }

    #[test]
    fn short_tokens_are_not_expanded() {
        let e = exp();
        assert!(e.expand(&normalize("a b c"), Lang::Und).is_empty());
    }

    #[test]
    fn empty_query_expands_to_nothing() {
        let e = exp();
        assert!(e.expand("", Lang::Und).is_empty());
        assert!(e.expand("   ", Lang::Und).is_empty());
    }

    #[test]
    fn variants_are_distinct() {
        let e = exp();
        let v = texts(&e.expand(&normalize("سونلغاز فاتورة كهرباء"), Lang::Ar));
        let mut sorted = v.clone();
        sorted.sort();
        sorted.dedup();
        assert_eq!(sorted.len(), v.len(), "duplicate variants: {v:?}");
    }

    #[test]
    fn expansion_is_deterministic() {
        let e = exp();
        let a = texts(&e.expand(&normalize("ch7al sonelgaz"), Lang::Ary));
        let b = texts(&e.expand(&normalize("ch7al sonelgaz"), Lang::Ary));
        assert_eq!(a, b);
    }

    #[test]
    fn meili_synonyms_are_symmetric() {
        // Meilisearch synonyms are directional, so every pair must be declared both ways or the
        // expansion works in one direction only — which is the subtle way this breaks.
        let syn = exp().meili_synonyms();
        let oran = syn.get("وهران").expect("wilaya should be present");
        assert!(oran.contains(&"oran".to_string()));
        let back = syn.get("oran").expect("reverse direction must exist");
        assert!(back.contains(&"وهران".to_string()));
    }

    #[test]
    fn meili_synonyms_never_map_a_term_to_itself() {
        for (term, equivalents) in exp().meili_synonyms() {
            assert!(
                !equivalents.contains(&term),
                "{term:?} maps to itself, which is a no-op that only costs index size"
            );
        }
    }

    #[test]
    fn meili_synonyms_are_normalised() {
        // They must match the form the index actually stores.
        for (term, equivalents) in exp().meili_synonyms() {
            assert_eq!(term, normalize(&term), "synonym key is not normalised");
            for e in equivalents {
                assert_eq!(e, normalize(&e), "synonym value is not normalised");
            }
        }
    }

    #[test]
    fn a_term_in_two_concepts_accumulates_both() {
        // `الجزائر` is both the capital and the country. Both senses should expand.
        let syn = exp().meili_synonyms();
        if let Some(v) = syn.get("الجزائر") {
            assert!(!v.is_empty());
            let mut sorted = v.clone();
            sorted.sort();
            sorted.dedup();
            assert_eq!(
                sorted.len(),
                v.len(),
                "accumulated synonyms not deduplicated"
            );
        }
    }
}
