#!/usr/bin/env bash
#
# Fetch and self-host the web fonts.
#
# Self-hosting is not a preference here, it is forced: the Content-Security-Policy is
# `default-src 'self'`, so a stylesheet or font file from a CDN is blocked outright. Loosening the
# policy to allow fonts.gstatic.com would also tell Google the IP of everyone who loads a results
# page, which is the single thing this engine exists to avoid.
#
# # Subsetting
#
# Google's CSS API already serves per-script files with `unicode-range`, which is the subsetting
# the design asks for and better than anything a naive `pyftsubset` run would produce. This keeps
# only the scripts actually served — Latin, Latin-ext for French, and Arabic — and discards
# Cyrillic, Greek and Vietnamese. Those three are roughly half the bytes and no reader of this
# engine needs them.
#
# The output is committed. A build that reaches the network to succeed is a build that fails when
# the network does, and font files change about once a year.
#
#   ./scripts/fetch-fonts.sh
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="web/public/fonts"
CSS="web/app/fonts.css"

# Which scripts each family is kept for.
#
# The Arabic family keeps *only* Arabic. It ships Latin subsets too, but IBM Plex Sans already
# covers Latin and the two are designed together — downloading a second Latin face so that Latin
# words inside an Arabic page come from the Arabic family would cost bytes to render the same
# shapes.
KEEP_SANS='^(latin|latin-ext)$'
KEEP_ARABIC='^arabic$'

# Requested separately, because the two families are not the same kind of font.
#
# IBM Plex Sans is variable: a `400..600` range gives one file per script covering every weight.
# IBM Plex Sans Arabic is **not** — asking it for a range returns an HTML error page rather than
# CSS, so it gets explicit weights. Requesting a range for both looked like it worked and quietly
# produced no Arabic at all, which is why the check further down exists.
SPEC_SANS="family=IBM+Plex+Sans:wght@400..600"
SPEC_ARABIC="family=IBM+Plex+Sans+Arabic:wght@400;600"
# A modern desktop UA, so the API serves woff2 rather than the ttf it gives unknown clients.
UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"

mkdir -p "$OUT"
fetch_css() {
  local css
  css=$(curl -fsS -m 30 -A "$UA" "https://fonts.googleapis.com/css2?$1&display=swap")
  # The API answers an unsupported request with an HTML page and a 200, so an empty check is not
  # enough — the body has to actually be CSS.
  if ! printf '%s' "$css" | grep -q '@font-face'; then
    echo "✗ fonts: $1 did not return CSS" >&2
    return 1
  fi
  printf '%s\n' "$css"
}

remote=$(
  fetch_css "$SPEC_SANS"
  fetch_css "$SPEC_ARABIC"
)

: >"$CSS.tmp"
cat >>"$CSS.tmp" <<'HEADER'
/*
 * Self-hosted web fonts.
 *
 * GENERATED by scripts/fetch-fonts.sh — do not edit by hand.
 *
 * Split per script with `unicode-range`, so a reader on an Arabic page never downloads the Latin
 * files and vice versa. `font-display: swap` because on a slow connection the alternative is
 * invisible text: the page is readable in a system face immediately and reflows once, which is
 * the right trade when the whole point is working on a bad connection.
 */
HEADER

count=0
kept=0
# The CSS is a sequence of `/* subset */` comments followed by @font-face blocks. Parsed with awk
# rather than a regex over the whole file, because a block spans lines and the subset name only
# appears in the comment above it.
while IFS='|' read -r subset family weight url; do
  count=$((count + 1))
  case "$family" in
  *Arabic*) rule="$KEEP_ARABIC" ;;
  *) rule="$KEEP_SANS" ;;
  esac
  if ! printf '%s' "$subset" | grep -qE "$rule"; then
    continue
  fi
  # The weight belongs in the name. Leaving it out collapsed the Arabic 400 and 600 onto one
  # filename, so both @font-face rules pointed at the same file and bold Arabic rendered as
  # regular. A variable face covers a range and is named `var` rather than by a single number.
  case "$weight" in
  *" "*) tag="var" ;;
  *) tag="$weight" ;;
  esac
  slug=$(printf '%s-%s-%s' "$family" "$tag" "$subset" | tr '[:upper:] ' '[:lower:]-')
  file="$OUT/$slug.woff2"
  curl -fsS -m 30 -A "$UA" "$url" -o "$file"
  kept=$((kept + 1))

  range=$(printf '%s' "$remote" | awk -v u="$url" '
    $0 ~ u { found = 1 }
    found && /unicode-range/ { sub(/^ *unicode-range: */, ""); sub(/;$/, ""); print; exit }')

  cat >>"$CSS.tmp" <<EOF

@font-face {
  font-family: '$family';
  font-style: normal;
  font-weight: $weight;
  font-display: swap;
  src: url('/fonts/$slug.woff2') format('woff2');
  unicode-range: $range;
}
EOF
done < <(printf '%s' "$remote" | awk '
  /^\/\* / { subset = $2 }
  /font-family:/ { gsub(/[;'"'"']/, ""); family = ""; for (i = 2; i <= NF; i++) family = family (i > 2 ? " " : "") $i }
  /font-weight:/ { sub(/^ *font-weight: */, ""); sub(/;$/, ""); weight = $0 }
  /src: url\(/ { match($0, /https:[^)]*/); url = substr($0, RSTART, RLENGTH); print subset "|" family "|" weight "|" url }
')

# Every family must have contributed. A missing family is the failure this whole script is most
# likely to have and the least likely to notice: the page still renders, in a fallback face, and
# only a reader of that script would ever see it.
for required in "IBM Plex Sans" "IBM Plex Sans Arabic"; do
  if ! grep -q "font-family: '$required';" "$CSS.tmp"; then
    echo "✗ fonts: no faces for '$required' — it would silently fall back" >&2
    rm -f "$CSS.tmp"
    exit 1
  fi
done

if [ "$kept" -eq 0 ]; then
  echo "✗ fonts: nothing matched out of $count faces — the API format probably changed" >&2
  rm -f "$CSS.tmp"
  exit 1
fi

# One file per face. A face sharing a file with another means a weight silently renders as the
# wrong one, which looks like a design choice rather than a bug.
files=$(find "$OUT" -name '*.woff2' | wc -l)
if [ "$files" -ne "$kept" ]; then
  echo "✗ fonts: $kept faces but $files files — two faces share a filename" >&2
  rm -f "$CSS.tmp"
  exit 1
fi

mv "$CSS.tmp" "$CSS"
bytes=$(du -sh "$OUT" | cut -f1)
echo "✓ fonts: $kept of $count faces kept in $files files ($bytes in $OUT)"
