//! The 58 wilayas.
//!
//! Static, compiled in, and correct at the 2019 reorganisation that created codes 49–58. Codes
//! change by decree, rarely, and a lookup table that needs a network call to answer "what is the
//! postal code for Béjaïa" would be a network call on every such search.
//!
//! Coordinates are the wilaya seat, which is what prayer times and weather should use — a
//! centroid of Tamanrasset province would sit in empty desert hundreds of kilometres from anyone.

use super::wilaya::Wilaya;

pub const WILAYAS: &[Wilaya] = &[
    Wilaya {
        code: 1,
        name_ar: "أدرار",
        name_fr: "Adrar",
        latitude: 27.8743,
        longitude: -0.2939,
        postal: "01",
        dial: "049",
    },
    Wilaya {
        code: 2,
        name_ar: "الشلف",
        name_fr: "Chlef",
        latitude: 36.165,
        longitude: 1.3345,
        postal: "02",
        dial: "027",
    },
    Wilaya {
        code: 3,
        name_ar: "الأغواط",
        name_fr: "Laghouat",
        latitude: 33.8,
        longitude: 2.865,
        postal: "03",
        dial: "029",
    },
    Wilaya {
        code: 4,
        name_ar: "أم البواقي",
        name_fr: "Oum El Bouaghi",
        latitude: 35.8753,
        longitude: 7.1135,
        postal: "04",
        dial: "032",
    },
    Wilaya {
        code: 5,
        name_ar: "باتنة",
        name_fr: "Batna",
        latitude: 35.5559,
        longitude: 6.1741,
        postal: "05",
        dial: "033",
    },
    Wilaya {
        code: 6,
        name_ar: "بجاية",
        name_fr: "Béjaïa",
        latitude: 36.7509,
        longitude: 5.0567,
        postal: "06",
        dial: "034",
    },
    Wilaya {
        code: 7,
        name_ar: "بسكرة",
        name_fr: "Biskra",
        latitude: 34.8504,
        longitude: 5.728,
        postal: "07",
        dial: "033",
    },
    Wilaya {
        code: 8,
        name_ar: "بشار",
        name_fr: "Béchar",
        latitude: 31.6167,
        longitude: -2.2167,
        postal: "08",
        dial: "049",
    },
    Wilaya {
        code: 9,
        name_ar: "البليدة",
        name_fr: "Blida",
        latitude: 36.4703,
        longitude: 2.8277,
        postal: "09",
        dial: "025",
    },
    Wilaya {
        code: 10,
        name_ar: "البويرة",
        name_fr: "Bouira",
        latitude: 36.3736,
        longitude: 3.902,
        postal: "10",
        dial: "026",
    },
    Wilaya {
        code: 11,
        name_ar: "تمنراست",
        name_fr: "Tamanrasset",
        latitude: 22.785,
        longitude: 5.5228,
        postal: "11",
        dial: "029",
    },
    Wilaya {
        code: 12,
        name_ar: "تبسة",
        name_fr: "Tébessa",
        latitude: 35.4042,
        longitude: 8.1244,
        postal: "12",
        dial: "037",
    },
    Wilaya {
        code: 13,
        name_ar: "تلمسان",
        name_fr: "Tlemcen",
        latitude: 34.8783,
        longitude: -1.315,
        postal: "13",
        dial: "043",
    },
    Wilaya {
        code: 14,
        name_ar: "تيارت",
        name_fr: "Tiaret",
        latitude: 35.3711,
        longitude: 1.317,
        postal: "14",
        dial: "046",
    },
    Wilaya {
        code: 15,
        name_ar: "تيزي وزو",
        name_fr: "Tizi Ouzou",
        latitude: 36.7118,
        longitude: 4.0458,
        postal: "15",
        dial: "026",
    },
    Wilaya {
        code: 16,
        name_ar: "الجزائر",
        name_fr: "Alger",
        latitude: 36.7538,
        longitude: 3.0588,
        postal: "16",
        dial: "021",
    },
    Wilaya {
        code: 17,
        name_ar: "الجلفة",
        name_fr: "Djelfa",
        latitude: 34.6704,
        longitude: 3.263,
        postal: "17",
        dial: "027",
    },
    Wilaya {
        code: 18,
        name_ar: "جيجل",
        name_fr: "Jijel",
        latitude: 36.819,
        longitude: 5.7667,
        postal: "18",
        dial: "034",
    },
    Wilaya {
        code: 19,
        name_ar: "سطيف",
        name_fr: "Sétif",
        latitude: 36.1898,
        longitude: 5.4108,
        postal: "19",
        dial: "036",
    },
    Wilaya {
        code: 20,
        name_ar: "سعيدة",
        name_fr: "Saïda",
        latitude: 34.8303,
        longitude: 0.1517,
        postal: "20",
        dial: "048",
    },
    Wilaya {
        code: 21,
        name_ar: "سكيكدة",
        name_fr: "Skikda",
        latitude: 36.879,
        longitude: 6.9067,
        postal: "21",
        dial: "038",
    },
    Wilaya {
        code: 22,
        name_ar: "سيدي بلعباس",
        name_fr: "Sidi Bel Abbès",
        latitude: 35.1878,
        longitude: -0.6308,
        postal: "22",
        dial: "048",
    },
    Wilaya {
        code: 23,
        name_ar: "عنابة",
        name_fr: "Annaba",
        latitude: 36.9,
        longitude: 7.7667,
        postal: "23",
        dial: "038",
    },
    Wilaya {
        code: 24,
        name_ar: "قالمة",
        name_fr: "Guelma",
        latitude: 36.4611,
        longitude: 7.4283,
        postal: "24",
        dial: "037",
    },
    Wilaya {
        code: 25,
        name_ar: "قسنطينة",
        name_fr: "Constantine",
        latitude: 36.365,
        longitude: 6.6147,
        postal: "25",
        dial: "031",
    },
    Wilaya {
        code: 26,
        name_ar: "المدية",
        name_fr: "Médéa",
        latitude: 36.2675,
        longitude: 2.7539,
        postal: "26",
        dial: "025",
    },
    Wilaya {
        code: 27,
        name_ar: "مستغانم",
        name_fr: "Mostaganem",
        latitude: 35.9315,
        longitude: 0.0892,
        postal: "27",
        dial: "045",
    },
    Wilaya {
        code: 28,
        name_ar: "المسيلة",
        name_fr: "M'Sila",
        latitude: 35.705,
        longitude: 4.5419,
        postal: "28",
        dial: "035",
    },
    Wilaya {
        code: 29,
        name_ar: "معسكر",
        name_fr: "Mascara",
        latitude: 35.3968,
        longitude: 0.14,
        postal: "29",
        dial: "045",
    },
    Wilaya {
        code: 30,
        name_ar: "ورقلة",
        name_fr: "Ouargla",
        latitude: 31.9494,
        longitude: 5.3255,
        postal: "30",
        dial: "029",
    },
    Wilaya {
        code: 31,
        name_ar: "وهران",
        name_fr: "Oran",
        latitude: 35.6969,
        longitude: -0.6331,
        postal: "31",
        dial: "041",
    },
    Wilaya {
        code: 32,
        name_ar: "البيض",
        name_fr: "El Bayadh",
        latitude: 33.6831,
        longitude: 1.0192,
        postal: "32",
        dial: "049",
    },
    Wilaya {
        code: 33,
        name_ar: "إليزي",
        name_fr: "Illizi",
        latitude: 26.4833,
        longitude: 8.4667,
        postal: "33",
        dial: "029",
    },
    Wilaya {
        code: 34,
        name_ar: "برج بوعريريج",
        name_fr: "Bordj Bou Arréridj",
        latitude: 36.0731,
        longitude: 4.7608,
        postal: "34",
        dial: "035",
    },
    Wilaya {
        code: 35,
        name_ar: "بومرداس",
        name_fr: "Boumerdès",
        latitude: 36.7663,
        longitude: 3.4772,
        postal: "35",
        dial: "024",
    },
    Wilaya {
        code: 36,
        name_ar: "الطارف",
        name_fr: "El Tarf",
        latitude: 36.7672,
        longitude: 8.3139,
        postal: "36",
        dial: "038",
    },
    Wilaya {
        code: 37,
        name_ar: "تندوف",
        name_fr: "Tindouf",
        latitude: 27.6742,
        longitude: -8.1478,
        postal: "37",
        dial: "049",
    },
    Wilaya {
        code: 38,
        name_ar: "تيسمسيلت",
        name_fr: "Tissemsilt",
        latitude: 35.6072,
        longitude: 1.8111,
        postal: "38",
        dial: "046",
    },
    Wilaya {
        code: 39,
        name_ar: "الوادي",
        name_fr: "El Oued",
        latitude: 33.3683,
        longitude: 6.8517,
        postal: "39",
        dial: "032",
    },
    Wilaya {
        code: 40,
        name_ar: "خنشلة",
        name_fr: "Khenchela",
        latitude: 35.4361,
        longitude: 7.1436,
        postal: "40",
        dial: "032",
    },
    Wilaya {
        code: 41,
        name_ar: "سوق أهراس",
        name_fr: "Souk Ahras",
        latitude: 36.2864,
        longitude: 7.9511,
        postal: "41",
        dial: "037",
    },
    Wilaya {
        code: 42,
        name_ar: "تيبازة",
        name_fr: "Tipaza",
        latitude: 36.5892,
        longitude: 2.4483,
        postal: "42",
        dial: "024",
    },
    Wilaya {
        code: 43,
        name_ar: "ميلة",
        name_fr: "Mila",
        latitude: 36.4503,
        longitude: 6.2644,
        postal: "43",
        dial: "031",
    },
    Wilaya {
        code: 44,
        name_ar: "عين الدفلى",
        name_fr: "Aïn Defla",
        latitude: 36.2639,
        longitude: 1.9678,
        postal: "44",
        dial: "027",
    },
    Wilaya {
        code: 45,
        name_ar: "النعامة",
        name_fr: "Naâma",
        latitude: 33.2667,
        longitude: -0.3167,
        postal: "45",
        dial: "049",
    },
    Wilaya {
        code: 46,
        name_ar: "عين تموشنت",
        name_fr: "Aïn Témouchent",
        latitude: 35.2978,
        longitude: -1.14,
        postal: "46",
        dial: "043",
    },
    Wilaya {
        code: 47,
        name_ar: "غرداية",
        name_fr: "Ghardaïa",
        latitude: 32.4911,
        longitude: 3.6736,
        postal: "47",
        dial: "029",
    },
    Wilaya {
        code: 48,
        name_ar: "غليزان",
        name_fr: "Relizane",
        latitude: 35.7372,
        longitude: 0.5556,
        postal: "48",
        dial: "046",
    },
    Wilaya {
        code: 49,
        name_ar: "تيميمون",
        name_fr: "Timimoun",
        latitude: 29.2639,
        longitude: 0.2306,
        postal: "49",
        dial: "049",
    },
    Wilaya {
        code: 50,
        name_ar: "برج باجي مختار",
        name_fr: "Bordj Badji Mokhtar",
        latitude: 21.3247,
        longitude: 0.9556,
        postal: "50",
        dial: "049",
    },
    Wilaya {
        code: 51,
        name_ar: "أولاد جلال",
        name_fr: "Ouled Djellal",
        latitude: 34.4167,
        longitude: 5.0667,
        postal: "51",
        dial: "033",
    },
    Wilaya {
        code: 52,
        name_ar: "بني عباس",
        name_fr: "Béni Abbès",
        latitude: 30.13,
        longitude: -2.17,
        postal: "52",
        dial: "049",
    },
    Wilaya {
        code: 53,
        name_ar: "عين صالح",
        name_fr: "In Salah",
        latitude: 27.1936,
        longitude: 2.46,
        postal: "53",
        dial: "029",
    },
    Wilaya {
        code: 54,
        name_ar: "عين قزام",
        name_fr: "In Guezzam",
        latitude: 19.5686,
        longitude: 5.7728,
        postal: "54",
        dial: "029",
    },
    Wilaya {
        code: 55,
        name_ar: "تقرت",
        name_fr: "Touggourt",
        latitude: 33.1,
        longitude: 6.0667,
        postal: "55",
        dial: "029",
    },
    Wilaya {
        code: 56,
        name_ar: "جانت",
        name_fr: "Djanet",
        latitude: 24.5544,
        longitude: 9.4844,
        postal: "56",
        dial: "029",
    },
    Wilaya {
        code: 57,
        name_ar: "المغير",
        name_fr: "El M'Ghair",
        latitude: 33.95,
        longitude: 5.9167,
        postal: "57",
        dial: "032",
    },
    Wilaya {
        code: 58,
        name_ar: "المنيعة",
        name_fr: "El Meniaa",
        latitude: 30.5833,
        longitude: 2.8833,
        postal: "58",
        dial: "029",
    },
];
